org.gradle.jvmargs=-Xmx2G

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=0.16.7-26.2
maven_group=com.example
archives_base_name=jefff-mod

# Dependencies

# Meteor (https://maven.meteordev.org)
meteor_version=26.2-SNAPSHOT

# Baritone (https://maven.meteordev.org)
baritone_version=26.2-SNAPSHOT

# XaeroPlus
xaeroplus_version=2.36.1+fabric-26.2

# XaeroWorldmap
xaeros_worldmap_version=fabric-26.2-1.46.0

# XaeroMinimap
xaeros_minimap_version=fabric-26.2-26.5.0
